#!/bin/sh

wallpaper="$(ls $HOME/.local/share/wallpapers | dmenu -c -l 10 -p "Select your wallpaper:")"

if [[ $wallpaper == "" ]]; then
	exit
fi
extension="$(cut -d "." -f2 <<<"$wallpaper")"
mkdir -p $HOME/.local/state/dwm
if [[ $extension != "jpg" ]]; then
	filename="$(cut -d "." -f1 <<<"$wallpaper")"
	cd $HOME/.local/share/wallpapers
	mogrify -format jpg $wallpaper
	mv $filename.jpg $HOME/.local/state/dwm/wallpaper.jpg
else
	cp $HOME/.local/share/wallpapers/$wallpaper $HOME/.local/state/dwm/wallpaper.jpg
fi
pkill -SIGTERM feh
feh --bg-fill $HOME/.local/state/dwm/wallpaper.jpg &
