#include <X11/Xlib.h>
#include <X11/Xresource.h>
#include <stdio.h>
#include <string.h>

#define TERMCOLS 16
#define BGCOLS 2

static char termcolors[][8] = { "#45475A", "#F38BA8", "#A6E3A1", "#F9E2AF",
                       "#89B4FA", "#F5C2E7", "#94E2D5", "#BAC2DE",
                       "#585B70", "#F38BA8", "#A6E3A1", "#F9E2AF",
                       "#89B4FA", "#F5C2E7", "#94E2D5", "#A6ADC8" };
static char bgcolors[][8]   = { "#1E1E2E", "#313244" };

typedef struct {
	char *name;
	char *dst;
} ResourcePref;

/*
 * Xresources preferences to load at startup
 */
ResourcePref resources[] = {
		{ "color0",      termcolors[0] },
		{ "color1",      termcolors[1] },
		{ "color2",      termcolors[2] },
		{ "color3",      termcolors[3] },
		{ "color4",      termcolors[4] },
		{ "color5",      termcolors[5] },
		{ "color6",      termcolors[6] },
		{ "color7",      termcolors[7] },
		{ "color8",      termcolors[8] },
		{ "color9",      termcolors[9] },
		{ "color10",     termcolors[10] },
		{ "color11",     termcolors[11] },
		{ "color12",     termcolors[12] },
		{ "color13",     termcolors[13] },
		{ "color14",     termcolors[14] },
		{ "color15",     termcolors[15] },
		{ "background0", bgcolors[1] },
		{ "background1", bgcolors[1] },
};

void
resource_load(XrmDatabase db, char *name, void *dst)
{
	char fullname[256];
	char *type;
	char color[8];
	XrmValue ret;

	snprintf(fullname, sizeof(fullname), "%s.%s", "dwmblocks", name);
	
	fullname[sizeof(fullname) - 1] = '\0';
	// printf("%d\n", XrmGetResource(db, fullname, "*", &type, &ret));
	if (XrmGetResource(db, fullname, "*", &type, &ret) == 0)
		return;
	if (ret.addr == NULL)
		return;

	strncpy(color, ret.addr, 7);
	color[sizeof(color) - 1] = '\0';
	strcpy(dst, color);
}

void
load_xresources(void)
{
	Display *display;
	char *resm;
	XrmDatabase db;
	ResourcePref *p;

	display = XOpenDisplay(NULL);
	resm = XResourceManagerString(display);
	if (!resm) {
		perror("XResourceManagerString is empty");
		return;
	}
	db = XrmGetStringDatabase(resm);
	for (p = resources; p < resources + sizeof(resources) / sizeof(resources[0]); p++)
		resource_load(db, p->name, p->dst);
	XCloseDisplay(display);
}

void print_header() {
	FILE *fp = fopen("colorscheme.h", "w");

	fprintf(fp, "/* Autogenerated file */\n#ifndef COLORSCHEME\n#define COLORSCHEME\n\n");

	for (int i = 0; i < TERMCOLS; i++)
		fprintf(fp, "#define CLR_%d \"^c%s^\"\n", i, termcolors[i]);

	for (int i = 0; i < BGCOLS; i++)
		fprintf(fp, "#define BG_%d \"^b%s^\"\n", i, bgcolors[i]);

	fprintf(fp, "#define NRM \"^d^\"\n\n#endif   /* COLORSCHEME */\n");
	fclose(fp);
}



int main(void) {
	load_xresources();
	print_header();
	return 0;
}
