#!/bin/sh

case $BLOCK_BUTTON in
	1)	mode="$(optimus-manager --status | grep Current | awk '{print $5}')"
		notify-send "Optimus Manager mode" "$(echo "$mode" | sed 's/.*/\u&/')";
esac




status="$(cat /sys/class/power_supply/BAT1/status)"
capacity=$(cat /sys/class/power_supply/BAT1/capacity)

if [[ $status == "Charging" ]]; then
	icon="^c#F9E2AF ^d^"
else
	if (( $capacity > 88 )); then
		icon="^c#A6E3A1^ ^d^"
	elif (( $capacity > 63 )); then
		icon="^c#A6E3A1^ ^d^"
	elif (( $capacity > 38 )); then
		icon="^c#A6E3A1^ ^d^"
	elif (( $capacity > 13 )); then
		icon="^c#F9E2AF^ ^d^"
	else
		icon="^c#F38BA8^ ^d^"
	fi
fi

printf "$icon\n"
