#!/bin/sh

mpirspath=$HOME/.local/state/dwm

case $BLOCK_BUTTON in
	1) mkdir -p $mpirspath
	dbus-send --print-reply --dest=org.freedesktop.DBus  /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep "mpris" | cut -d "." -f4- | cut -d "\"" -f1 | xmenu | cat > $mpirspath/mprisclient;;
	2) setsid -f st -e sh -c pulsemixer;;
	3) setsid -f easyeffects;;
esac


volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
volume=$(awk '{print $1*$2}' <<<"${volume} 100")

if [[ "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep "MUTED")" == "" ]]; then
	if (( $volume > 66 )); then
		icon=""
	elif (( $volume > 33 )); then
		icon=""
	else
		icon=""
	fi
else
	icon=""
fi

printf "^c#A6E3A1^$icon $volume%%^d^\n"
