/* Autogenerated file */
#ifndef COLORSCHEME
#define COLORSCHEME

#define CLR_0 "^c#45475A^"
#define CLR_1 "^c#F38BA8^"
#define CLR_2 "^c#A6E3A1^"
#define CLR_3 "^c#F9E2AF^"
#define CLR_4 "^c#89B4FA^"
#define CLR_5 "^c#F5C2E7^"
#define CLR_6 "^c#94E2D5^"
#define CLR_7 "^c#BAC2DE^"
#define CLR_8 "^c#585B70^"
#define CLR_9 "^c#F38BA8^"
#define CLR_10 "^c#A6E3A1^"
#define CLR_11 "^c#F9E2AF^"
#define CLR_12 "^c#89B4FA^"
#define CLR_13 "^c#F5C2E7^"
#define CLR_14 "^c#94E2D5^"
#define CLR_15 "^c#A6ADC8^"
#define NRM "^d^"

#endif   /* COLORSCHEME */
